# -*- coding: utf-8 -*-
"""hello

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ni1hCNaJqVAHpgigsR3bhK0ziS-NDdNM
"""

name = str(input("what's yory name?"))
age = int(input("What's your age?"))

print(f"Hello {name}! You are {age} years old.")